name: Docker Image CI

on:
  pull_request:
    branches: [ "master","Production"]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    -
      name:  Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - 
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - 
      name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: ./webApp-backend    
      
    -
      name: push backend
      uses: docker/build-push-action@v6
      with:
          file: ./webApp-backend/Dockerfile
          push: true
          context: ./webApp-backend  # Build context includes JAR now
          tags: sanjayapradeep/bodimabackend:latest
    -
      name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
          file: ./webapp-frontend/Dockerfile
          push: true
          tags: sanjayapradeep/bodimafrontend:latest
