name: Java CI with Gradle

on:
  push:
    branches: [ "developer-*" ]
  pull_request:
    branches: [ "development","master","Production" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build Java spring boot
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
              
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: ./webApp-backend
